name: Docker Workflow
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@master
      - id: build_version
        name: Build ${{ github.ref }}
        run: docker build -t tarocch1/mirai-http-center:${{ github.ref }} .
      - id: build_latest
        name: Build latest
        run: docker build -t tarocch1/mirai-http-center:latest .
      - id: login
        name: Docker login
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_ACCESSTOKEN }}"
      - id: push_version
        name: Push ${{ github.ref }}
        run: docker push tarocch1/mirai-http-center:${{ github.ref }}
      - id: push_latest
        name: Push ${{ github.ref }}
        run: docker push tarocch1/mirai-http-center:latest
