name: Release Workflow
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@master
      - id: setup_go
        name: Setup go
        uses: actions/setup-go@master
        with:
          go-version: '1.14'
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@master
        with:
          node-version: 12
      - id: npm_ci
        name: npm ci
        run: npm ci
      - id: tag_name
        name: Get tag name
        uses: ./.github/actions/tag-name
        with:
          ref: ${{ github.ref }}
      - id: build
        name: Build
        run: bash ./.github/actions/release/build.sh
        env:
          VERSION: ${{ steps.tag_name.outputs.tag }}
          COMMIT_ID: ${{ github.sha }}
      - id: compress
        name: Compress
        run: bash ./.github/actions/release/compress.sh
      - id: create_release
        name: Create Release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - id: upload_release_asset_mirai-http-center_linux_32
        name: Upload mirai-http-center_linux_32.zip
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mirai-http-center_linux_32.zip
          asset_name: mirai-http-center_linux_32.zip
          asset_content_type: application/zip
      - id: upload_release_asset_mirai-http-center_linux_64
        name: Upload mirai-http-center_linux_64.zip
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mirai-http-center_linux_64.zip
          asset_name: mirai-http-center_linux_64.zip
          asset_content_type: application/zip
      - id: upload_release_asset_mirai-http-center_linux_arm
        name: Upload mirai-http-center_linux_arm.zip
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mirai-http-center_linux_arm.zip
          asset_name: mirai-http-center_linux_arm.zip
          asset_content_type: application/zip
      - id: upload_release_asset_mirai-http-center_linux_arm64
        name: Upload mirai-http-center_linux_arm64.zip
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mirai-http-center_linux_arm64.zip
          asset_name: mirai-http-center_linux_arm64.zip
          asset_content_type: application/zip
      - id: upload_release_asset_mirai-http-center_macos
        name: Upload mirai-http-center_macos.zip
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mirai-http-center_macos.zip
          asset_name: mirai-http-center_macos.zip
          asset_content_type: application/zip
      - id: upload_release_asset_mirai-http-center_windows_32
        name: Upload mirai-http-center_windows_32.zip
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mirai-http-center_windows_32.zip
          asset_name: mirai-http-center_windows_32.zip
          asset_content_type: application/zip
      - id: upload_release_asset_mirai-http-center_windows_64
        name: Upload mirai-http-center_windows_64.zip
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mirai-http-center_windows_64.zip
          asset_name: mirai-http-center_windows_64.zip
          asset_content_type: application/zip
